### PR TITLE
reside-151 update json schemas

### PR DESCRIPTION
**Pull request by hillalex**
* changes "const" -> "enum" just to make my ts generator happy
* changes "requiredProperties" -> "reuqired" which is the correct keyword
* fixes the listed required properties by changing "success" -> "status"
* adds .schema to the file extension for schemas. this isn't necessary, just the convention we've gone with elsewhere but feel free to explain why we shouldn't do this.

### CODE REVIEW

**Review by richfitz — COMMENTED** [review]
This looks good, except the possible change from .schema.json to .json - @r-ash and I discussed this early on in scoping this package and we don't feel strongly about it. However, it just feels a bit redundant to have

```
schema/Data.schema.json
```

and then either in the code saying

```
pkgapi_returning_json("Data.schema")
```

or forcing everyone to use .schema.json and `pkgapi_returning_json("Data")`

Options here include:

* We can do this change if it is less disruptive for you and and take either route above with referencing schemas in the R code (probably the former)
* We could do this change and look for "Data.schema.json" or "Data.json" given a string "Data"
* We could keep the pkgapi current behaviour and update your code to look for "Data.json"

What do you think?

**Comment by hillalex** [comment]
>
> Options here include:
> 
> * We can do this change if it is less disruptive for you and and take either route above with referencing schemas in the R code (probably the former)
> * We could do this change and look for "Data.schema.json" or "Data.json" given a string "Data"
> * We could keep the pkgapi current behaviour and update your code to look for "Data.json"
> 
> What do you think?

It's not actually disruptive for me, it's trivial to change my script to look for .json so happy to leave these schema definition files as .json.

I think it'd be nice though if

```
pkgapi_returning_json("Data")
``` 

looked for the file at both `Data.json` and `Data.schema.json`, since the latter is a common convention. What do you think?

**Comment by r-ash** [comment]
> > Options here include:
> > 
> > * We can do this change if it is less disruptive for you and and take either route above with referencing schemas in the R code (probably the former)
> > * We could do this change and look for "Data.schema.json" or "Data.json" given a string "Data"
> > * We could keep the pkgapi current behaviour and update your code to look for "Data.json"
> > 
> > What do you think?
> 
> It's not actually disruptive for me, it's trivial to change my script to look for .json so happy to leave these schema definition files as .json.
> 
> I think it'd be nice though if
> 
> ```
> pkgapi_returning_json("Data")
> ```
> 
> looked for the file at both `Data.json` and `Data.schema.json`, since the latter is a common convention. What do you think?

Looks like examples within schema specification are often using `.json` only but that most people tend to use `.schema.json` as a convention. I'd be up for looking for files with either extension if its going to be used more widely than just us. Also maybe an argument for just having to specify the extension too `pkgapi_returning_json("Data.schema.json")`. The specification refers to schema as full filename throughout - https://tools.ietf.org/html/draft-zyp-json-schema-04

**Comment by hillalex** [comment]
Yeah I can see the case for requiring a full filename with extension (in theory users might have files with other conventions, I've seen references to .jsd and .jschema.) Although I suppose you could infer the extension as .json iff no explicit extension is provided.

**Comment by richfitz** [comment]
So given a name 'x' we look for, in order of preference:

* 'x'
* 'x.json'
* 'x.schema.json'

**Comment by hillalex** [comment]
> So given a name 'x' we look for, in order of preference:
> 
> * 'x'
> * 'x.json'
> * 'x.schema.json'

That seems like useful behaviour to me :+1:

**Comment by richfitz** [comment]
That's down as https://mrc-ide.myjetbrains.com/youtrack/issue/RESIDE-152

**Review by richfitz — APPROVED** [review]

**Pull request merged**
